---
version: "3.8"
services:
  datasynthesisdb:
    image: docker.io/postgres:latest
    restart: always
    environment:
      POSTGRES_USER: datasynthesis
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: datasynthesis
  quarkus:
    image: maven
    environment:
      DATABASE_HOST: datasynthesisdb
    volumes:
      - "./:/app:Z,delegated"
      # Mounting user's local .m2-directory,
      # for custom settings.xml and for caching dependencies.
      - "~/.m2:/root/.m2:Z,delegated"
    ports:
      - 5005:5005 # Debug port
      - 8080:8080 # Backend HTTP server port
    working_dir: /app
    command: "mvn quarkus:dev"
    links:
      - datasynthesisdb
    depends_on:
      - datasynthesisdb
